services:
 - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.25.5
    - secure: OwaQa4EugQUDdFRU0Km5qVvO2EUiYUrPq1mPDUiX2xLs1ZcT40PvYoWraXxhZx9+CyFNofYmNO0aI5HBIkdqQGtmia8i0bnr2lsV9hQ5gzzIIf/fqAVp5ttWviTX5KVtZ7QISVpN7VaB+W1flrPwUgS0zwl+WviYRHyLdKjqziNa7oZ5vTJiPZJxjjiIAek5SyU1cDUEjd9EIffn6LXOJ0YnriBSrUzEHk5eMWLO86fXvDMAs9DD3g0jZt9VhrRRhD40Eg+s1Fmr1MDCGUHpt6zCSMQ7OIflneZt0t+zKPPA9WRyavq3zYA41S1oI5ywPgB8T5gUcSupI+y7ROboz3Mo+LMB/a7NYgS59Q9F4DR+9jo8Qt5nI9Px8ITd3Tw9NBJVp85dR2Y18aL0ytzAO6dT5H30kwFnN7Lb9bpootDcqtKIEg2GqmWFCsfANMgEx0C+YO34tXQzKdtje8vS92px1sgjHvYEm0Ls/9hDn/uEangnLjGb5RCUBowWhJtjfU25/WYLIdXOOqBqGkFW0I/7IXQDrrFVcuR8ieBsql5BrzPFbXN96hlj50zk47kIG1Q0fCOTprlaBtEkgO8+fC4chMNHKpafgwFfNbNkJ7N7dIWvGWs8IuNGsUIaqQDofpH0rk0GIlq7UpLUyIrkY3NQHk0fvAsmkwNW7l+tPKE=
    - secure: MvmUfWGwvXxzKa2j41qSmCGhTYOTFycCxDGIPVSevegIWUxmcdlvEckF08yH4Nl9egMs1r/31BC/EwEwYlzMZNtC1KNC2Nwy5N1RZHqKwFpofA5ikbk+v0rnhFXj/nvNaQXdNijaRbAn2vOjSiri5BwTIGkgN2pb1HmflrgGK7cd+M7QD6K2YIHBOpV02kqG9X9xx3dTXd8LuAq2tI10+urHZh22Q7YH12XOvgg2+/dXXPuZSRlCUK3uLNLDgJZ6Z6dPwXGaqY8QTnuoeIkDKSjoZ7dGjX5ug6xGRRdfA559eCbmuAJo9uliJ4OpdgIEVtXHaa8qUPvJ3I2JYCXDJWC/tMDJa+D+f7AaPJIyUrGI9BSKbRVfie0VxAqwwX78IXB0tq7Wsl4R4/wNygdcUHppN68iLj1CpPOjYdA097QN6CP/5GadD+FrJVCy98Tt1bUawiFhaclkGtl7MRsdR+WrPudcOYt3ruGCH8a8EdFFIYFIC7FZRLv4ispwbH84VM8Ak17NwzGdxwnnb5dFYsaVRps6DWwmSccNIEpfy4ye1vWz4r/lu5JuqUobdAJ2QYPE6afA8CCQ+g9bqrGzFZNRYBG6og0CCWSZ90MvMu1Yfus80ncxmd3g4+3d9NJ4I9CcMb7yROjYzNC9Viu+oam4alqRYr9ExTcFxOs67s4=

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose version
  - echo "Login into DOcker Hub"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export GIT_SHA=`git rev-parse --short HEAD`
  - echo "Building commit $GIT_SHA"

jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script:
      - docker-compose build db
      - docker-compose build test-postgresql
      - docker-compose run test-postgresql
    - stage: tests
      name: "Static Analysis"
      script:
      - docker-compose build static-analysis
      - docker-compose run static-analysis
    - stage: push
      script:
      - docker-compose build server
      - docker tag albums_server:latest vasilevvd/albums-backend:$GIT_SHA
      - docker push vasilevvd/albums-backend:$GIT_SHA
      - docker tag albums_server:latest vasilevvd/albums-backend:$TRAVIS_BRANCH
      deploy:
      - provider: script
        script: docker push vasilevvd/albums-backend:$TRAVIS_BRANCH
        on:
          branch: master
      - provider: script
        script: docker push vasilevvd/albums-backend:$TRAVIS_TAG
        on:
          tags: True

